# version: '3'
# services:
#   web:
#     build: .
#     command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#   mongodb:
#     image: mongo
#     volumes:
#       - mongodb_data:/data/db
# volumes:
#   mongodb_data:

version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kaancan
      - MONGO_INITDB_ROOT_PASSWORD=kaanCAN1989!!
volumes:
  mongodata:
